"""empty message

Revision ID: 72a637a551b2
Revises: 400fd42cfb88
Create Date: 2024-10-26 18:47:57.836221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a637a551b2'
down_revision = '400fd42cfb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    op.drop_table('landlord')
    op.drop_table('tenant')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tenant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_phone_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('house_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('house_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('deposit_paid', sa.FLOAT(), nullable=False),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('receipt_number_deposit', sa.VARCHAR(length=100), nullable=True),
    sa.Column('rent_amount', sa.FLOAT(), nullable=False),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('rent_receipt_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('property_id', sa.INTEGER(), nullable=False),
    sa.Column('rent_paid', sa.FLOAT(), nullable=True),
    sa.Column('amount_due', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number_deposit'),
    sa.UniqueConstraint('rent_receipt_number'),
    sa.UniqueConstraint('tenant_phone_number')
    )
    op.create_table('landlord',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('landlord_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('property',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('property_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('landlord_id', sa.INTEGER(), nullable=False),
    sa.Column('is_occupied', sa.BOOLEAN(), nullable=True),
    sa.Column('house_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('number_of_rooms', sa.INTEGER(), nullable=False),
    sa.Column('occupied_rooms', sa.INTEGER(), nullable=False),
    sa.Column('price_bedsitter', sa.FLOAT(), nullable=True),
    sa.Column('price_one_bedroom', sa.FLOAT(), nullable=True),
    sa.Column('price_two_bedroom', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlord.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
